# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Login to Dockerhub
      uses: docker/login-action@v3
      with:
        username: slehmstedt
        password: ${{ secrets.DOCKER_PAT }}
    - name: Setup Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push on Dockerhub
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: slehmstedt/gymreservationsystem
    - name: Pull image from EC2
      uses: cross-the-world/ssh-pipeline@v1.2.0
      with:
        host: ${{ vars.EC2_PUBLIC_DOMAIN }}
        user: ${{ vars.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          docker stop gym-reservation-system
          docker rm gym-reservation-system
          docker run --name=gym-reservation-system -d slehmstedt/gymreservationsystem --pull=always
      
      
    
    
      
